version: "3.8"

services:
  mysql_db:
    image: mysql:8.0.41-oracle
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:alpine
    networks:
      - backend

  index:
    build:
      context: ./servers
      dockerfile: Dockerfile
    command: ["node", "IndexApp.js"]
    networks:
      - backend
    deploy:
      replicas: 2

  auth:
    build:
      context: ./servers
      dockerfile: Dockerfile
    command: ["node", "AuthApp.js"]
    networks:
      - backend
    deploy:
      replicas: 2

  cart:
    build:
      context: ./servers
      dockerfile: Dockerfile
    command: ["node", "CartApp.js"]
    networks:
      - backend
    deploy:
      replicas: 2

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - index
      - auth
      - cart
    deploy:
      replicas: 2

volumes:
  mysql_data:

networks:
  backend:
