version: "3.8"

services:
  mysql:
    image: mysql:8.0.41-oracle
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend


  krakend:
    image: devopsfaith/krakend
    container_name: krakend
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "8080:8080"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  index:
    build:
      context: ./servers
      dockerfile: Dockerfile
    container_name: index
    ports:
      - "3001:3000"
    command: ["node", "IndexApp.js"]
    depends_on:
      - mysql
      - redis
    networks:
      - backend

  auth:
    build:
      context: ./servers
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "3002:3000"
    command: ["node", "AuthApp.js"]
    depends_on:
      - mysql
      - redis
    networks:
      - backend

  cart:
    build:
      context: ./servers
      dockerfile: Dockerfile
    container_name: cart
    ports:
      - "3003:3000"
    command: ["node", "CartApp.js"]
    depends_on:
      - mysql
      - redis
    networks:
      - backend

  nginx:
    build: ./nginx
    container_name: nginxProxy
    ports:
      - "80:80"
    depends_on:
      - index
      - auth
      - cart
    networks:
      - backend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
